// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDEA2ioQZ0HT3PU156If_tKCmfeB_Ya7M',
    appId: '1:731861479604:web:05d1c2a4d91b62889f27e1',
    messagingSenderId: '731861479604',
    projectId: 'carify-2adf7',
    authDomain: 'carify-2adf7.firebaseapp.com',
    storageBucket: 'carify-2adf7.firebasestorage.app',
    measurementId: 'G-3VT5QCDDSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKexQIUBvDH94AMBzUBGTTyYaSOHVFHPM',
    appId: '1:731861479604:android:a1d3c3990da9b5909f27e1',
    messagingSenderId: '731861479604',
    projectId: 'carify-2adf7',
    storageBucket: 'carify-2adf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB1RmnM9iws9_NCSD719rL5ybYhB30juk',
    appId: '1:731861479604:ios:823dce71e831bc049f27e1',
    messagingSenderId: '731861479604',
    projectId: 'carify-2adf7',
    storageBucket: 'carify-2adf7.firebasestorage.app',
    iosBundleId: 'com.example.epicecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB1RmnM9iws9_NCSD719rL5ybYhB30juk',
    appId: '1:731861479604:ios:823dce71e831bc049f27e1',
    messagingSenderId: '731861479604',
    projectId: 'carify-2adf7',
    storageBucket: 'carify-2adf7.firebasestorage.app',
    iosBundleId: 'com.example.epicecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDEA2ioQZ0HT3PU156If_tKCmfeB_Ya7M',
    appId: '1:731861479604:web:ad3bdf82b9946b169f27e1',
    messagingSenderId: '731861479604',
    projectId: 'carify-2adf7',
    authDomain: 'carify-2adf7.firebaseapp.com',
    storageBucket: 'carify-2adf7.firebasestorage.app',
    measurementId: 'G-PHSK5BW0PM',
  );
}
